branch-defaults:
  master:
    environment: REST-api
    group_suffix: null
environment-defaults:
  REST-api:
    branch: null
    repository: null
global:
  application_name: REST-api
  branch: null
  default_ec2_keyname: null
  default_platform: python
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
